spring.application.name=PaymentService

server.port=8083

eureka.client.service.url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
spring.jpa.hibernate.ddl-auto=update

