spring.application.name=OrderService

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
spring.jpa.hibernate.ddl-auto=update